language: node_js
node_js:
  - 5.4.1
before_script:
  - npm install -g webpack jsx-typescript firebase-tools tsd
  - npm install
  - tsd install
script:
  - npm run build
  - npm run test
after_success:
  - mkdir /home/travis/tmp
  - echo -e "${FIREBASE_EMAIL}\n${FIREBASE_PASSWORD}" | firebase deploy
