language: node_js
node_js:
  - 5.4.1
before_script:
  - npm install -g webpack jsx-typescript firebase-tools tsd
  - npm install
  - tsd install
script:
  - npm run build
  - npm run test
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
after_failure:
  - cat /home/travis/build/EvAlex/RoboCoach/npm-debug.log
