language: node_js
node_js:
  - 5.4.1
before_script:
  - npm install -g webpack jsx-typescript firebase-tools tsd
  - npm install
  - tsd install
script:
  - npm run build
after_success:
  - firebase deploy --email ${FIREBASE_EMAIL} --password ${FIREBASE_PASSWORD}
